raise ZeroDivisionError('My cause exception')
